import { environment } from '../../../environments/environment';

export const ECARE_API = {
  ALLERGIES: '/api/allergies',
  APPLIED_PROTOCOLS: '/api/immunization_protocols',
  CONDITIONS: '/api/conditions',
  DIAGNOSTICS: '/api/diagnostics',
  ENCOUNTERS: '/api/patient_encounters',
  GOAL_OUTCOMES: '/api/goal_outcomes',
  GOALS: '/api/goals',
  GUIDED_ENCOUNTERS: '/api/guided_encounters',
  IMMUNIZATIONS_DRUGS: '/api/immunization_drugs',
  IMMUNIZATIONS: '/api/immunizations',
  INTERVENTIONS: '/api/interventions',
  MEDICAL_CODES: '/api/medical_codes',
  MEDICATIONS: '/api/medications',
  MEDICATION_ORDERS: '/api/medication_orders',
  META: '/api/meta',
  NOTES: '/api/notes',
  PATIENT_MEASUREMENT_RECORDS: '/api/patient_measurement_records',
  PATIENT_MEASUREMENTS: '/api/patient_measurements',
  PATIENTS: '/api/patients',
  PERSONS: '/api/persons',
  PRACTITIONERS: '/api/practitioners',
  REPORTS: {
    LOW_ADHERENCE: '/api/reports/low_adherence',
    MISSED_MEDICATIONS: '/api/reports/missed_medication',
    MULTI_DOSE_OPPORTUNITIES: '/api/reports/multi_dose_opportunities',
    OPPORTUNITY_INTERVENTIONS: '/api/reports/opportunity_interventions',
    SUPPRESSED_OPPORTUNITIES: '/api/reports/suppressed_opportunities',
  },
  STATE_REGISTRY: '/api/state_registry',
  SURVEY_RECORDS: '/api/survey_records',
  SURVEYS: '/api/surveys',
  TASKS: '/api/todos',
  TRANSMISSIONS: '/api/transmissions',
  FHIR_JSON: '/api/transmissions/download',
};

export const APP_API = {
  ACTIVITIES: `${environment.api.appApi}/api/v2/activities`,
  ANNOUNCEMENTS: `${environment.api.appApi}/api/v2/announcements`,
  ASSIST_APP_SETTINGS: `${environment.api.appApi}/api/v2/live_integration/settings`,
  ASSIST_DOWNLOAD: `${environment.api.appApi}/api/v2/assist_download`,
  ASSIST_NOTIFICATION_SETTINGS: `${environment.api.appApi}/api/v2/live_integration/notification_settings`,
  CAMPAIGN_EVENTS: `${environment.api.appApi}/api/v2/campaign_events`,
  CAMPAIGNS: `${environment.api.appApi}/api/v2/campaigns`,
  COGNITO_AUTH: `${environment.api.appApi}/api/v2/cognito_auth`,
  CONFIG: `${environment.api.appApi}/api/v2/config`,
  DRUG_LIST_DRUGS: `${environment.api.appApi}/api/v2/drug_list_drugs`,
  DRUG_LISTS: `${environment.api.appApi}/api/v2/drug_lists`,
  DRUGS: `${environment.api.appApi}/api/v2/drugs`,
  FILES: `${environment.api.appApi}/api/v2/files`,
  INSIGHTS_ANALYTICS: `${environment.api.appApi}/api/v2/insights/analytics`,
  LOGOUT: `${environment.api.appApi}/api/v2/logout`,
  NOTES: `${environment.api.appApi}/api/v2/notes`,
  OPPORTUNITIES: `${environment.api.appApi}/api/v2/opportunities`,
  OPPORTUNITY_PHASES: `${environment.api.appApi}/api/v2/opportunity_phases`,
  PASSWORDS: `${environment.api.appApi}/api/v2/passwords`,
  PATIENT_OUTREACH: `${environment.api.appApi}/api/v2/patient_outreach`,
  PATIENTS: `${environment.api.appApi}/api/v2/patients`,
  PHARMACIES: `${environment.api.appApi}/api/v2/pharmacies`,
  PLANS: `${environment.api.appApi}/api/v2/plans`,
  PORTAL_ENROLL_IDS: `${environment.api.appApi}/api/v2/portal_enroll_ids`,
  POSTCODES: `${environment.api.appApi}/api/v2/postcodes`,
  PRACTITIONERS: `${environment.api.appApi}/api/v2/lookup/doctors`,
  RECORDINGS: `${environment.api.appApi}/api/v2/recordings`,
  SQS_ANALYTICS: `${environment.api.appApi}/api/v2/sqs_analytics`,
  STORE_FEATURES: `${environment.api.appApi}/api/v2/store_features`,
  SUBSIDIES: `${environment.api.appApi}/api/v2/subsidies`,
  TEMPLATES: `${environment.api.appApi}/api/v2/templates`,
  TOKEN_EXCHANGE: `${environment.api.appApi}/api/v2/token_exchange`,
  TOKEN_REFRESH: `${environment.api.appApi}/api/v2/refresh_tokens`,
  TOKENS: `${environment.api.appApi}/api/v2/tokens`,
  USERS: `${environment.api.appApi}/api/v2/users`,
  VENDORS: `${environment.api.appApi}/api/v2/vendors`,
};
